import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} antialiased`}>
        <Sidebar />
        <div className="ml-0 lg:ml-64">
          {children}
        </div>
      </body>
    </html>
  );
}
